# Configuración para stylepc.lat
server {
    listen 80;
    server_name stylepc.lat;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri /index.html;
    }
}

# Configuración para panel.stylepc.lat
server {
    listen 80;
    server_name panel.stylepc.lat;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri /index.html;
    }
}

# Configuración para web.stylepc.lat
server {
    listen 80;
    server_name web.stylepc.lat;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri /index.html;
    }
}
